[package]
name = "zk-time-capsule-2025"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-sdk = { version = "4.1.3" } # Используем версию, указанную в ошибке
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }